# Basic Config
spring.application.name=api-gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# -------------------------
# AUTO ROUTING (KEEP)
# -------------------------
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# -------------------------
# MANUAL ROUTE (USER - GIVEN)
# -------------------------
spring.cloud.gateway.routes[0].id=user-manual-route
spring.cloud.gateway.routes[0].uri=lb://user-ms
spring.cloud.gateway.routes[0].predicates[0]=Path=/manual-user/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/manual-user/(?<segment>.*), /${segment}

# -------------------------
# ADD THIS (USER DIRECT ROUTE)
# -------------------------
spring.cloud.gateway.routes[1].id=user-route
spring.cloud.gateway.routes[1].uri=lb://user-ms
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/user/(?<segment>.*), /${segment}

# -------------------------
# ADD THIS (ACCOUNT ROUTE)
# -------------------------
spring.cloud.gateway.routes[2].id=account-route
spring.cloud.gateway.routes[2].uri=lb://accountmng-ms
spring.cloud.gateway.routes[2].predicates[0]=Path=/account/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/account/(?<segment>.*), /${segment}